dist: trusty
sudo: false

language: go
go_import_path: github.com/omniscale/imposm3

go:
  - "1.10.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x" # we use this for releases, see deploy.on.condition below
  - tip

matrix:
  allow_failures:
    - go: tip
      fast_finish: true

env:
  global:
    - GEOS_VERSION=3.7.3
    - LEVELDB_VERSION=1.22
    # NOTE increase DEPS_REVISION everytime one of the compiled deps changes!
    - DEPS_REVISION=3
    # PREFIX is where we install our compiled deps
    - PREFIX=${HOME}/local-${DEPS_REVISION}

    # tell Go to find our compiled deps
    - CGO_CFLAGS=-I${PREFIX}/include
    - CGO_LDFLAGS=-L${PREFIX}/lib
    - LD_LIBRARY_PATH=${PREFIX}/lib

    # PKG_DIR is where we assemble the final package for releases
    - PKG_DIR=/tmp/imposm_packaging

    - PGUSER=postgres

    # enable ccache by updating PATH
    - PATH=/usr/lib/ccache:$PATH
    - CCACHE_TEMPDIR=/tmp/.ccache-temp

cache:
  directories:
    - ${HOME}/.ccache
    - ${PREFIX}

addons:
    postgresql: "9.5"
    apt:
      # List of whitelisted in travis packages for ubuntu-trusty can be found here:
      #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
      packages:
        - postgresql-9.5-postgis-2.3
        - osmosis
        - chrpath

before_script:
  - psql -U postgres -c 'create database travis' || true
  - psql -U postgres -c "create extension if not exists postgis"
  - psql -U postgres -c "create extension if not exists hstore"


before_install:
  - echo "TRAVIS_GO_VERSION = " ${TRAVIS_GO_VERSION}
  - ccache --show-stats

  # build GEOS
  - |
    if [[ ! -e ${PREFIX}/lib/libgeos_c.so ]]; then
      curl -fsSL http://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2 | \
        tar -jxf - -C ${HOME}/build
      cd ${HOME}/build/geos-${GEOS_VERSION}
      ./configure --prefix=$PREFIX
      make -j2
      make install
    fi

  # build LevelDB
  - |
    if [[ ! -e ${PREFIX}/lib/libleveldb.so ]]; then
      mkdir -p ${HOME}/build/leveldb
      curl -fsSL https://github.com/google/leveldb/archive/${LEVELDB_VERSION}.tar.gz | \
        tar -zxf - --strip-components 1 -C ${HOME}/build/leveldb
      mkdir -p ${HOME}/build/leveldb/build
      cd ${HOME}/build/leveldb/build
      cmake .. -DBUILD_SHARED_LIBS=1 -DCMAKE_BUILD_TYPE=Release && make -j 2
      mkdir -p ${PREFIX}/{lib,include}
      cp -R ${HOME}/build/leveldb/build/liblevel* ${PREFIX}/lib/
      cp -R ${HOME}/build/leveldb/include/leveldb ${PREFIX}/include/
    fi

  - ccache --show-stats

script:
  - cd ${TRAVIS_BUILD_DIR}
  - LEVELDB_POST_121=1 make

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p ${PKG_DIR}/lib

  # copy files
  - cp imposm ${PKG_DIR}
  - ln -s imposm ${PKG_DIR}/imposm3
  - cp README.md ${PKG_DIR}
  - cp example-mapping.json ${PKG_DIR}/mapping.json

  # copy/link libs
  - cd ${PREFIX}/lib
  - cp libgeos_c.so ${PKG_DIR}/lib
  - ln -s libgeos_c.so ${PKG_DIR}/lib/libgeos_c.so.1
  - cp libgeos.so ${PKG_DIR}/lib
  - ln -s libgeos.so ${PKG_DIR}/lib/libgeos-${GEOS_VERSION}.so
  - cp -R libleveldb.so* ${PKG_DIR}/lib

  # update RPATH of libgeos_c.so so that is points to our libgeos.so
  - chrpath ${PKG_DIR}/lib/libgeos_c.so -r '${ORIGIN}'

  # create tar.gz
  - BUILD_VERSION=`${PKG_DIR}/imposm version`-linux-x86-64
  - mv ${PKG_DIR} /tmp/imposm-${BUILD_VERSION}
  - cd /tmp && tar zcvf imposm-${BUILD_VERSION}.tar.gz imposm-${BUILD_VERSION}

  # move back to build dir for deploy
  - cd ${TRAVIS_BUILD_DIR}

deploy:
  provider: releases
  api_key:
    secure: e/ORBKHrg04y/FJGx1y4s1VT/GSiVHgofVSBXDEwtGzWaoVO0U1HYUt6vgxaIXVi+U1QY/NFljhSQDuE04IkojoOc8Iojqwh6XCgPxVzyJbbUglyFFsvN9A6V8ybpcGNKMLzaSxkuapVTp+1qTxPuyuuavCSGOwbkFxW4ma17xd/Vv6oWSS0EuEFNOaGOxfEPJysrs0xQdsUlGnfzdeD4h0x/B1GhxKbUKxIaF1THsCvZGZolz975YZMI49q/XtqSweSXXNr7N4EKFceWlIHEEBgVvi5LEFmin8/lG/gMKGw9T4yjVkL8fZfdzTd58a4NktRLpZn54V6da5i2yAtCYjUKHUs8jueLttr+bnhNKwaP7ElJRXwWmUOznbt0wOjvFW344jWb+yIFSdeaVRHYRqb+Iecm6NDJBTsMebndwAux1HVBGFPYKSZELCvY0d4gG3sTNgoIYS84iJOZPxI9zcsWO+6Ieo5Sm5fFtfr5qC0XO2mqOofziipOGqH0h8QAGzhUYhpleDCVX5qLucfuYOvcXNR7+btUy619GeUg/ea1D7xzjmn3E/8HspiaHG4yE5pdKfW/9Lw20UEkQR5HRL5hhBUEUoP+dHYPDqUXIHraX6MlH2AnCcnYfkRKRivLKW4Qyw2OXJ07ZmBaEqjDP1KcXIpA8IKswXQkwnNvG4=
  file: /tmp/imposm-${BUILD_VERSION}.tar.gz
  skip_cleanup: true
  on:
    repo: amatissart/imposm3
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.15
